syntax = "proto3";

package kihan.internal;

message CreateRoomReq {
    string player_list_json = 1;
}

message CreateRoomRsp {
    int32 err_code = 1;
    int32 room_id = 2;
}

message GameResultNtf {
    int32 room_id = 1;
    uint32 p1_uid = 2;
    uint32 p2_uid = 3;
    uint32 winner_uid = 4; // 0 for draw
}

service GameControlService {
    // Lobby -> Game
    rpc CreateRoom(CreateRoomReq) returns (CreateRoomRsp);
}

// In case Game needs to call Lobby (ReportGameResult)
service LobbyControlService {
    rpc ReportGameResult(GameResultNtf) returns (CreateRoomRsp); // Reuse CreateRoomRsp for simple err_code
}
